name: thai_region
description: The flutter project for provide province, district, sub-district in thailand.
version: 1.0.0
homepage: https://github.com/skwcrd/thai_region

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
